import type { Config } from "tailwindcss";

// Tokens verbatim from designs/prototypes/chat.html + dashboard.html
// (tailwind-config block) and designs/design-system.md — the interactive
// reference UI is the source of truth (docs/frontend-design.md §2).
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3f465c",
        tertiary: "#000000",
        "on-tertiary-container": "#75859d",
        "secondary-container": "#2170e4",
        "on-tertiary-fixed": "#0b1c30",
        "inverse-surface": "#2d3133",
        secondary: "#0058be",
        "outline-variant": "#c6c6cd",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#adc6ff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-container": "#eceef0",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        outline: "#76777d",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#bec6e0",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#d3e4fe",
        "on-error": "#ffffff",
        "primary-container": "#131b2e",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-secondary": "#ffffff",
        "surface-tint": "#565e74",
        "on-secondary-fixed-variant": "#004395",
        "on-primary-container": "#7c839b",
        surface: "#f7f9fb",
        "on-primary-fixed": "#131b2e",
        "on-secondary-fixed": "#001a42",
        "surface-container-lowest": "#ffffff",
        primary: "#000000",
        "on-surface-variant": "#45464d",
        "secondary-fixed": "#d8e2ff",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#bec6e0",
        background: "#f7f9fb",
        error: "#ba1a1a",
        "tertiary-container": "#0b1c30",
        "primary-fixed": "#dae2fd",
        "on-secondary-container": "#fefcff",
        // Legacy alias — on-surface ink for headings/body (docs §2):
        "ink-700": "#1E293B",
        "ink-900": "#191C1E",
        // Sidebar palette — .sb-root CSS vars in globals.css (sidebar spec
        // §2): neutral grayscale, light/dark via prefers-color-scheme.
        sb: {
          bg: "var(--sb-bg)",
          hover: "var(--sb-hover)",
          selected: "var(--sb-selected)",
          pressed: "var(--sb-pressed)",
          border: "var(--sb-border)",
          text: "var(--sb-text)",
          "text-secondary": "var(--sb-text-secondary)",
          "text-muted": "var(--sb-text-muted)",
          icon: "var(--sb-icon)",
          "input-bg": "var(--sb-input-bg)",
          "input-border": "var(--sb-input-border)",
        },
        success: "#10B981",
        warning: "#F59E0B",
        white: "#FFFFFF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "margin-desktop": "32px",
        "stack-sm": "8px",
        unit: "4px",
        "margin-mobile": "16px",
        "stack-xl": "48px",
        gutter: "24px",
        "stack-md": "16px",
        "stack-xs": "4px",
        "stack-lg": "24px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        display: ["Geist", "Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter"],
        "title-lg": ["Geist"],
        "headline-lg": ["Geist"],
        "headline-md": ["Geist"],
        "label-md": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Geist"],
        "display-lg": ["Geist"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
};

export default config;